server:
  port: 8082
  tomcat:
    keep-alive-timeout: 60000
    max-keep-alive-requests: -1
spring:
  application:
    name: matching-evaluation
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: matching-evaluation
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/callog_evaluation}
      database: ${MONGODB_EVALUATION:callog_evaluation}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: ${TRACING_ENABLED:false}
    sampling:
      probability: 1.0   # 모든 요청에 대한 데이터를 수집하겠다.
  otlp:
    tracing:
      endpoint: ${JAEGER_URL:http://localhost:4318/v1/traces}
      transport: http

custom:
  n8n:
    webhook-url: ${N8N_URL:http://localhost:5678/webhook}
    evaluation-endpoint: ${EVALUATION_ENDPOINT:/evaluation}

app:
  kafka:
    topics:
      evaluation-start: evaluation.start
      evaluation-collect: evaluation.collect
      evaluation-completed: evaluation.completed
      evaluation-failed: evaluation.failed
      evaluation-start-dlq: evaluation.start.dlq
      evaluation-collect-dlq: evaluation.collect.dlq
eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka/}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
