server:
  port: 8082
  tomcat:
    keep-alive-timeout: 60000
    max-keep-alive-requests: -1
spring:
  application:
    name: ai-evaluation
  data:
    mongodb:
      uri: ${MONGODB_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

custom:
  n8n:
    webhook-url: ${N8N_URL}
    evaluation-endpoint: ${EVALUATION_ENDPOINT}
