apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: callog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
      - name: backend
        image: tahcy/callogapp-1.0-blue
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: callog-backend-config
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: callog-backend-config