description = 'ai-judge'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.apache.pdfbox:pdfbox:3.0.3'
    implementation 'org.mongodb:mongodb-driver-sync'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'software.amazon.awssdk:s3:2.25.70'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // 유레카
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // 일반 서비스들은 표준 WebMVC 기반이므로 webmvc-ui 추가
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
}
