jwt:
  key: ${JWT_SECRET}

spring:
  application:
    name: spring-gw
  cloud:
    gateway:
      routes:
        - id: gateway-local-info
          uri: noop://localhost
          predicates:
            - Path=/gw/**
          filters:
            - StripPrefix=1

        # ai 판사
        - id: ai-judge-actuator
          uri: lb://ai-judge
          predicates:
            - Path=/aijudge/actuator/**
          filters:
            - StripPrefix=1

        - id: ai-judge
          uri: lb://ai-judge
          predicates:
            - Path=/aijudge/**

        # ai 평가

        - id: ai-evaluation-actuator
          uri: lb://ai-evaluation
          predicates:
            - Path=/evaluation/actuator/**
          filters:
            - StripPrefix=1

        - id: matching-evaluation
          uri: lb://matching-evaluation
          predicates:
            - Path=/evaluation/**

        - id: app
          uri: lb://app
          predicates:
            - Path=/**
          filters:
            - JwtFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}