export const campaignLabels = {
  createCampaign: '캠페인 생성',
  editCampaign: '캠페인 수정',
  period: '기간',
  partners: '파트너',
  purpose: '목적',
  goals: '목표',
}

export const campaignStatusMeta = {
  // 현재 사용 상태 (STATUS_OPTIONS 기준)
  draft:        { label: '초안',       tone: 'gray'    },
  in_progress:  { label: '진행중',     tone: 'emerald' },
  recruiting:   { label: '모집중',     tone: 'blue'    },
  review:       { label: '검토중',     tone: 'amber'   },
  completed:    { label: '완료',       tone: 'indigo'  },
  closed:       { label: '종료',       tone: 'slate'   },
  // 하위 호환 (구 데이터)
  live:         { label: '진행중',     tone: 'emerald' },
  active:       { label: '진행중',     tone: 'emerald' },
  planned:      { label: '초안',       tone: 'gray'    },
  in_review:    { label: '검토중',     tone: 'amber'   },
  at_risk:      { label: '위험',       tone: 'amber'   },
  paused:       { label: '일시중지',   tone: 'gray'    },
  partner_done: { label: '파트너완료', tone: 'indigo'  },
}

export const campaignModalText = {
  eyebrowCreate: campaignLabels.createCampaign,
  eyebrowEdit: campaignLabels.editCampaign,
  saveChanges: '변경사항 저장',
  close: '닫기',
  name: '캠페인명',
  namePlaceholder: '프리미엄 초청 캠페인',
  tags: '태그',
  tagsPlaceholder: 'VIP, 호텔, SNS',
  startDate: '시작일',
  endDate: '종료일',
  purposePlaceholder: '캠페인 목표와 운영 배경을 입력하세요',
  goalsPlaceholder: '리뷰 목표, 완료율, 산출 목표 등을 요약하세요',
  hint: '저장한 캠페인은 워크스페이스에 바로 반영됩니다.',
  cancel: '취소',
}

export const campaignSidebarText = {
  sidebar: '캠페인 사이드바',
  goToDashboard: '대시보드로 이동',
  campaignList: '캠페인 목록',
  reorderHint: '드래그해서 순서를 바꿀 수 있습니다',
  campaignBrief: '캠페인 개요',
  noPartners: '등록된 파트너 없음',
  emptyPurpose: '아직 목적이 입력되지 않았습니다.',
  emptyGoals: '아직 목표가 입력되지 않았습니다.',
  campaignActions: '캠페인 작업',
  editDescription: '개요, 기간, 파트너 정보를 수정합니다',
  reopenCampaign: '캠페인 재개',
  reopenDescription: '캠페인을 다시 진행 상태로 전환합니다',
  markAsComplete: '완료 처리',
  completeDescription: '캠페인을 종료하고 완료로 기록합니다',
  resumeCampaign: '캠페인 재개',
  resumeDescription: '진행과 리뷰 추적을 다시 시작합니다',
  pauseCampaign: '캠페인 일시 중지',
  pauseDescription: '진행 업데이트를 잠시 중지합니다',
  pausedAlert: '중단된 캠페인',
  completedBadge: '완료된 캠페인',
  folderLabel: '완료 캠페인 보관함',
  folderEmpty: '보관된 완료 캠페인이 없습니다.',
  folderHelper: '완료된 캠페인을 이곳으로 드래그해 보관하세요.',
  folderDropReady: '보관함에 넣기',
  folderDropBlocked: '완료된 캠페인만 보관할 수 있습니다.',
  folderTitle: '캠페인 보관함',
  folderSummary: '완료한 캠페인을 개인별 순서와 보관 상태로 관리합니다.',
  folderOpen: '열기',
  folderRestore: '보관함에서 꺼내기',
  folderStatus: '보관됨',
}
