package org.example.backend.notification.model;

public enum NotificationType {
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_UPDATED,
    REVIEW_REQUESTED,
    REVIEW_APPROVED,
    REVIEW_REJECTED,
    DEADLINE_24H,
    DEADLINE_1H,
    DEADLINE_OVERDUE,
    CAMPAIGN_INVITED,
    CAMPAIGN_INVITATION_ACCEPTED,
    CAMPAIGN_INVITATION_REJECTED,
    CAMPAIGN_MEMBER_ADDED,
    SYSTEM
}
